// All job listings are fictional demonstration data. Replace this array when connecting an API.
window.DEMO_JOBS = [
  { company: '(주)넥스트커머스', industry: 'IT · 플랫폼', title: '핀테크 웹 프론트엔드 React 개발자', salary: '연 4,200만 ~ 5,200만', location: '서울 강남구 · 역삼역 3분', hours: '주 5일 (09:30~18:30)', career: '경력 2년 ~ 5년', deadline: '마감 7일 전', tags: ['유연근무제', 'React', 'TypeScript', 'Node.js'], description: '더 편리한 금융 경험을 만드는 웹 서비스를 개발합니다. React 기반 UI 개발, 서비스 성능 개선, 디자이너 및 백엔드 개발자와의 협업을 담당합니다.' },
  { company: '스튜디오 온도', industry: '디자인 · 콘텐츠', title: '함께 경험을 설계할 프로덕트 디자이너', salary: '연 3,800만 ~ 5,000만', location: '서울 성동구 · 성수역 5분', hours: '주 5일 (10:00~19:00)', career: '경력 1년 ~ 4년', deadline: '마감 12일 전', tags: ['유연근무제', 'Figma', 'UX/UI', '자율복장'], description: '사용자 리서치부터 화면 설계까지 제품의 전 과정을 함께합니다. 사용성 문제를 발견하고 프로토타입으로 아이디어를 검증합니다.' },
  { company: '그린루트', industry: '커머스 · 라이프스타일', title: '지속 가능한 일상을 전하는 콘텐츠 마케터', salary: '연 3,200만 ~ 4,200만', location: '서울 마포구 · 합정역 4분', hours: '주 5일 (09:00~18:00)', career: '신입 · 경력 3년 이하', deadline: '마감 5일 전', tags: ['신입가능', '콘텐츠', '브랜딩', '식대지원'], description: '브랜드의 이야기를 콘텐츠로 만들고 고객에게 전달합니다. SNS 채널 운영, 캠페인 기획, 콘텐츠 성과 분석 업무를 담당합니다.' },
  { company: '데이터웨이브', industry: 'IT · 데이터', title: '서비스의 다음 방향을 찾는 데이터 분석가', salary: '연 4,000만 ~ 5,500만', location: '경기 성남시 · 판교역 8분', hours: '주 5일 · 선택근무제', career: '경력 2년 이상', deadline: '마감 9일 전', tags: ['하이브리드', 'SQL', 'Python', '교육지원'], description: '제품 데이터를 분석해 팀의 의사결정을 돕습니다. 지표 설계, 대시보드 구축, 실험 분석을 함께할 동료를 찾습니다.' },
  { company: '메이커스랩', industry: 'IT · 소프트웨어', title: '안정적인 서비스를 만드는 백엔드 개발자', salary: '연 4,500만 ~ 6,000만', location: '서울 구로구 · 구로디지털단지역 5분', hours: '주 5일 (10:00~19:00)', career: '경력 3년 이상', deadline: '마감 14일 전', tags: ['Java', 'Spring', '코드리뷰', '장비지원'], description: '서비스 API와 데이터 구조를 설계하고 운영합니다. 안정성과 확장성을 함께 고민하며 개발 문화를 만들어 갑니다.' },
  { company: '로컬커넥트', industry: '플랫폼 · 지역 서비스', title: '동네와 사람을 연결하는 서비스 운영 매니저', salary: '연 3,000만 ~ 3,800만', location: '서울 영등포구 · 당산역 6분', hours: '주 5일 (09:00~18:00)', career: '신입 · 경력 무관', deadline: '마감 6일 전', tags: ['신입가능', '서비스운영', '온보딩', '식대지원'], description: '파트너 온보딩과 고객 문의를 담당합니다. 사용자 피드백을 정리하고 더 나은 서비스 운영 프로세스를 만듭니다.' }
];
